# Production docker-compose.yml for IMPES Application
# This file is for production deployments using pre-built images from GitHub Container Registry

services:
  nginx_proxy:
    image: ghcr.io/USERNAME/impes-nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
    restart: unless-stopped

  frontend:
    image: ghcr.io/USERNAME/impes-frontend:latest
    container_name: react_frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: ghcr.io/USERNAME/impes-api:latest
    container_name: node_api
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: db
      DB_USER: impesUser
      DB_PASSWORD: Admin2010impes
      DB_NAME: imbesdb
    restart: unless-stopped

  mysql_db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: imbesdb
      MYSQL_USER: impesUser
      MYSQL_PASSWORD: Admin2010impes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

# Instructions:
# 1. Replace USERNAME with your actual GitHub username
# 2. Copy this file to your production machine
# 3. Run: docker-compose -f docker-compose.production.yml up -d
# 4. Access your app at: http://YOUR-SERVER-IP/impes/
